apiVersion: v2
name: brewet-chart
description: A Helm chart for deploying the RHOAI Brewet plugin
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - rhoai
  - openshift-ai
  - plugin
  - brewet
home: https://github.com/rh-ai-community-plugins/brewet
sources:
  - https://github.com/rh-ai-community-plugins/brewet
maintainers:
  - name: rh-ai-community-plugins
    url: https://github.com/rh-ai-community-plugins
